### ISSUE TITLE
training data

### ISSUE THREAD

**Issue by dcassineletgo** [aws-samples/amazon-sagemaker-object-detection-from-scratch#1]
Where can we find the training data ?

**Comment by tasiogr** [comment]
Hi, the goal of the [webinar referred](https://pages.awscloud.com/EMEA-field-OE-ai-ml-web-day-2019-reg-event.html) is to build your own data set using an AWS DeepLens device (or any other AWS IoT Greengrass enabled camera) and Amazon SageMaker Ground Truth. There are other examples where you can build an object detection model using public datasets, such as https://aws.amazon.com/blogs/machine-learning/identifying-bird-species-on-the-edge-using-the-amazon-sagemaker-built-in-object-detection-algorithm-and-aws-deeplens/
Would that be ok for you?
